### ISSUE TITLE
Add pageSize parameter

### ISSUE THREAD

**Issue by Leonigas** [Elompenta/antpool-php-api#16]
Hi

according to the do (https://www.antpool.com/user/apiGuild.htm) for each endpoint we can set the parameter "pageSize" wich is the number of records per page, and default is 10.

When we have a lot of worker and the parameter is set to 10, it is not possible to get all the workers (we have more thant 40 workers).

So we have to put the parameter pageSize to 100 to get it work !

I changed the code like following in the method get() : 
        $post_fields = array(
            'key' => $this->key,
            'nonce' => $nonce,
            'signature' => $hmac,
            'coin' => $coin,
            'pageSize' => 100
        );

But it is just to make it work, can you do the enhancement ?

Thanks

**Comment by Elompenta** [comment]
this is not the best way to do this, because the param "pageSize" can only used if you make an get() with the type "workers".
If you make an `get('account')`, it will results in an error. Please check the API docu again.

What we have todo, is to extend the get() function on the requested amount of items if available in the specific method.

Can you prepare a Pull Request?

**Comment by Leonigas** [comment]
Ok I understand,

how can we extends the get() function ? by testing the $type value (to 'workers') and adding a optional parameter ?

**Comment by Elompenta** [comment]
i think a good option is to adding an optional parameter and use the paramater if the type will support  it.

**Comment by Elompenta** [comment]
closed - please check my post: https://github.com/Elompenta/antpool-php-api/commit/7ae015d0d2c5bfe71b6b0eb224073d5dd5175a22
